/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentps;

/**
 *
 * @author Asus
 */
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class RentalForm extends javax.swing.JFrame {

    /**
     * Creates new form RentalForm
     */
    
    private psmanager manager = new psmanager();
    private int totalPendapatan = 0;
    private Map<String, Timer> countdownTimers = new HashMap<>();
    public RentalForm() {
        initComponents();
        kelasCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUnitCombo();
            }
        });
        tipePSCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String tipe = (String) tipePSCombo.getSelectedItem();
                if (tipe.equals("PS5")) {
                    kelasCombo.setSelectedItem("VIP");
                } else {
                    kelasCombo.setSelectedItem("Normal");
                }
                updateUnitCombo();
    }
});
        
    }
    private void updateUnitCombo() {
        String tipe = (String) tipePSCombo.getSelectedItem();
        String kelas = (String) kelasCombo.getSelectedItem();
        if (tipe == null || kelas == null) {
            return;
        }
        unitCombo.removeAllItems();
        ArrayList<ps> available = manager.getAvailablePS(tipe, kelas);
        if (available.isEmpty()) {
        unitCombo.addItem("Tidak ada unit tersedia");
        } else {
            for (ps ps : available) {
                unitCombo.addItem(ps.getId());
            }
        }
    }

    private void updateUnitDisewaCombo() {
        unitDisewaCombo.removeAllItems();
        for (ps ps : manager.getDaftarPS()) {
            if (!ps.isTersedia()) {
                unitDisewaCombo.addItem(ps.getId());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sewaButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        tipePSCombo = new javax.swing.JComboBox<>();
        kelasCombo = new javax.swing.JComboBox<>();
        unitCombo = new javax.swing.JComboBox<>();
        unitDisewaCombo = new javax.swing.JComboBox<>();
        durasiField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PS 4 SEHAT 5 SEMPURNA");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tipe PS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 63, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Kelas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 45, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Unit Tersedia");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 113, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Durasi (jam)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 260, 104, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Unit Disewa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 160, 101, 25);

        sewaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sewaButton.setText("SEWA");
        sewaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sewaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sewaButton);
        sewaButton.setBounds(113, 321, 103, 37);

        batalButton.setBackground(new java.awt.Color(255, 51, 51));
        batalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        batalButton.setText("BATALKAN");
        batalButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batalButton);
        batalButton.setBounds(424, 321, 104, 37);

        tipePSCombo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tipePSCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PS4", "PS5" }));
        tipePSCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipePSComboActionPerformed(evt);
            }
        });
        getContentPane().add(tipePSCombo);
        tipePSCombo.setBounds(170, 70, 80, 39);

        kelasCombo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kelasCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "VIP" }));
        kelasCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasComboActionPerformed(evt);
            }
        });
        getContentPane().add(kelasCombo);
        kelasCombo.setBounds(170, 130, 104, 40);

        unitCombo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        unitCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitComboActionPerformed(evt);
            }
        });
        getContentPane().add(unitCombo);
        unitCombo.setBounds(170, 190, 171, 41);

        unitDisewaCombo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        getContentPane().add(unitDisewaCombo);
        unitDisewaCombo.setBounds(410, 190, 180, 39);

        durasiField.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        getContentPane().add(durasiField);
        durasiField.setBounds(170, 260, 97, 26);

        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(21, 376, 588, 149);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\SMT 2\\PBO\\lgfinal1.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 95, 80);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel8.setText("RENTAL PS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, -10, 260, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\SMT 2\\PBO\\projectpbo\\bg3.jpg")); // NOI18N
        jLabel6.setText(".");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 630, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipePSComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipePSComboActionPerformed
        // Taruh logika dari sewaPS() di sini:
        updateUnitCombo();
        
    }//GEN-LAST:event_tipePSComboActionPerformed

    private void sewaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaButtonActionPerformed
        // TODO add your handling code here:
        
        String id = (String) unitCombo.getSelectedItem();
    if (id == null) {
        JOptionPane.showMessageDialog(this, "Tidak ada unit tersedia.");
        return;
    }

    int durasi;
    try {
        durasi = Integer.parseInt(durasiField.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan durasi yang valid.");
        return;
    }

    ps ps = manager.getPSUnitById(id);
    if (ps != null && ps.isTersedia()) {
        ps.setTersedia(false);
        int harga = ps.getHargaPerJam();
        int total = harga * durasi;
        totalPendapatan += total;

        String currentText = outputArea.getText();
        int index = currentText.lastIndexOf("Total Pendapatan:");
        if (index != -1) {
            currentText = currentText.substring(0, index).trim();
            outputArea.setText(currentText + "\n");
        }

        outputArea.append("Disewa: " + id + " selama " + durasi + " jam. Total: Rp" + total + "\n");
        outputArea.append("\nTotal Pendapatan: Rp" + totalPendapatan);

        int durasiDetik = durasi * 60 * 60;
        final String psId = id;
        final int[] sisaDetik = { durasiDetik };

        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                sisaDetik[0]--;
                int jam = sisaDetik[0] / 3600;
                int menit = (sisaDetik[0] % 3600) / 60;
                int detik = sisaDetik[0] % 60;
                String waktuStr = String.format("%02d:%02d:%02d", jam, menit, detik);

                String[] lines = outputArea.getText().split("\n");
                for (int i = 0; i < lines.length; i++) {
                    if (lines[i].contains("Disewa: " + psId)) {
                        String baseLine = lines[i].split("\\|")[0].trim();
                        lines[i] = baseLine + " | Waktu tersisa: " + waktuStr;
                        break;
                    }
                }

                StringBuilder newText = new StringBuilder();
                for (String line : lines) {
                    newText.append(line).append("\n");
                }
                outputArea.setText(newText.toString().trim());

                if (sisaDetik[0] <= 0) {
                    ((Timer) e.getSource()).stop();
                    ps.setTersedia(true);
                    updateUnitCombo();
                    updateUnitDisewaCombo();
                }
            }
        });
        timer.start();
        countdownTimers.put(id, timer);

        updateUnitCombo();
        updateUnitDisewaCombo();
    }
    }//GEN-LAST:event_sewaButtonActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
         String id = (String) unitDisewaCombo.getSelectedItem();
    if (id == null) {
        JOptionPane.showMessageDialog(this, "Tidak ada unit yang disewa");
        return;
    }

    ps ps = manager.getPSUnitById(id);
    if (ps != null && !ps.isTersedia()) {
        ps.setTersedia(true);

        // HENTIKAN TIMER DI SINI
        Timer timer = countdownTimers.get(id);
        if (timer != null) {
            timer.stop();
            countdownTimers.remove(id);
        }

        // Hapus baris dari outputArea yang mengandung id tersebut
        String[] lines = outputArea.getText().split("\n");
        StringBuilder newOutput = new StringBuilder();
        for (String line : lines) {
            if (!line.contains("Disewa: " + id)) {
                newOutput.append(line).append("\n");
            }
        }
        outputArea.setText(newOutput.toString().trim());

        updateUnitCombo();
        updateUnitDisewaCombo();
    }
    }//GEN-LAST:event_batalButtonActionPerformed

    private void unitComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitComboActionPerformed

    private void kelasComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JTextField durasiField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kelasCombo;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JButton sewaButton;
    private javax.swing.JComboBox<String> tipePSCombo;
    private javax.swing.JComboBox<String> unitCombo;
    private javax.swing.JComboBox<String> unitDisewaCombo;
    // End of variables declaration//GEN-END:variables
    
}
